site_name: 述真阁
site_url: https://leostrange05.github.io/

nav:
  - 🏠 主页: index.md

  - 🛠️ 技术博客:
    - 导览: blog/index.md
    - 标签汇总: blog/tags.md

  - 🎵 音乐空间:
    - 导览: musicspace/index.md

  - 🔗 网上邻居:
    - 网上邻居: friends.md

  - ℹ️ 关于本站:
    - 本站志: diary.md

  # - Branch one:
  #   - home: Tab1/index.md
  #   - page: Tab1/page-1.md
  #   - another page:
  #     - subpage: Tab1/new/page-3.md

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: lime
      toggle:
        icon: material/brightness-3
        name: 切换至浅色模式

  font:
    text: Ubuntu
    code: Jetbrains Mono
  language: zh
  icon:
    logo: simple/meteor
    annotation: material/arrow-right-circle-outline
    
  favicon: assets/favicon.ico
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.annotate

plugins:
  - search

  - git-revision-date-localized:
      type: timeago  # 可选: date, datetime, timeago
      locale: zh  # 设置为中文显示
      fallback_to_build_date: true  # 如果git信息不可用，使用构建日期

  - statistics:
      page_check_metadata: date

  - blog:
      blog_dir: musicspace
      blog_toc: true
      post_readtime: false
    
  - blog:
      blog_dir: blog
      blog_toc: true
      post_readtime: false

  - tags:
      enabled: true
      tags_hierarchy: true
      
markdown_extensions:  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
                     
  - attr_list         # annotation
  - md_in_html
  - pymdownx.superfences

  - attr_list         # button

  - pymdownx.highlight: # code block
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.superfences # content tab
  - pymdownx.tabbed:
      alternate_style: true

  - tables            # table
  - toc:
      permalink: true
                      # icon emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - attr_list          # image
  - md_in_html
  - pymdownx.blocks.caption

  - footnotes          # footnote

  - pymdownx.critic    # formatting: highlight, insert, delete
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@200..900&display=swap
  - stylesheets/extra.css

extra:
  comments: true
  social:
    - icon: material/email
      link: mailto:cheng08032005@outlook.com
      name: 电子邮件
    - icon: fontawesome/brands/github
      link: https://github.com/leostrange05
      name: GitHub
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/32313515/leostrange
      name: Stack Overflow
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/profiles/76561198888960145/
      name: Steam
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0009-0003-4712-4764)
      name: ORCID